```{r}
library(dplyr)
library(tidyverse)
library(Rtsne)
library(plotly)


```

```{r}
vol_plrs_a = read.csv('Men_Statistics/men_best_attackers.csv')
vol_plrs_blk = read.csv('Men_Statistics/men_best_blockers.csv')
vol_plrs_ser = read.csv('Men_Statistics/men_best_servers.csv')
vol_plr_sco = read.csv('Men_Statistics/men_best_scores.csv')
vol_plr_res = read.csv('Men_Statistics/men_best_recievers.csv')
vol_plr_dig = read.csv('Men_Statistics/men_best_diggers.csv')
```

```{r}
plr_name = intersect(intersect(vol_plrs_a$Name, vol_plr_sco$Name), vol_plrs_ser$Name)
vol_plrs_ser[is.na(vol_plrs_ser)]=0
```

```{r}

best_WS = list(player = vol_plrs_a[,2:4],
               attack = vol_plrs_a[,-c(1,8,9)],
               serve = vol_plrs_ser[,-1],
               score = vol_plr_sco[,-c(1,5:7)])


best_WS_data = best_WS %>% reduce(full_join, by=c('ShirtNumber', 'Name', 'Team'))

best_WS_data[is.na(best_WS_data)]=0
```

```{r}
player_n = as.data.frame(plr_name)
colnames(player_n) = "Name"

best_WS = list(funame = player_n,
               player = vol_plrs_a[,2:4],
               attack = vol_plrs_a[,-c(1,2,4,8)],
               serve = vol_plrs_ser[,-c(1,2,4)],
               score = vol_plr_sco[,-c(1,2,4,5:7)])


best_WS_data = best_WS %>% reduce(full_join, by='Name')

best_WS_data[is.na(best_WS_data)]=0

```

```{r}
#find the 10 players who are more than the data 
check_more_id = c()
for(i in 1:260){
  ch = 0
  for(plr in plr_name){
    if(best_WS_data$Name[i]==plr){
      ch = ch + 1
    }
  }
  if(ch==0){
    check_more_id = rbind(check_more_id,i)
  }
}

check_more_id = as.vector(check_more_id)


best_WS_data = best_WS_data[-c(251:260),]
```

```{r}
write.csv(best_WS_data,"DataFrame/Players_stats2020.csv", 
          row.names = FALSE)
write.csv(plr_info, 
          "DataFrame/Player_infoVolleybox2023.csv",
          row.names = FALSE)
```

```{r}
#224 players

best_WS_data = best_WS_data[-plr_id_uncom,]

#then combining the players' info. and their stats.




```

```{r}
best_WS_dataScale = as.data.frame(cbind(best_WS_data[,1:3],scale(as.matrix(best_WS_data[,4:13]))))
```

# First map

```{r}
set.seed(19970608)
library(Rtsne)
library(plotly)
tsneVol = Rtsne(best_WS_data[,-c(1:3)], check_duplicates = FALSE)

visualtsneFIVB = as.data.frame(cbind(tsneVol$Y, best_WS_data$Team))
colnames(visualtsneFIVB) = c("V1","V2","Team")

visualtsneFIVB = transform(visualtsneFIVB, V1 = as.numeric(V1), V2 = as.numeric(V2))

plot_ly(visualtsneFIVB, x = ~V1, y = ~V2, color = plr_info$Position, text = best_WS_data$Name)


FIVBplot_DataPosition = plot_ly(visualtsneFIVB, x = ~V1, y = ~V2, color = plr_info$Position, text = best_WS_data$Name)
```

#Attack

```{r}
best_WS$attack %>% mutate(percentage = round(Shots/Spikes, digits = 2))

```

## Data cleaning for players info.

```{r}
for(i in 1:224){
  for(j in 2:6){
    if(grepl("Right", plr_info[i,j])==TRUE){
      plr_info[i,7] = "Right"
      plr_info[i,j] = 0
    }else if(grepl("Left", plr_info[i,j])==TRUE){
      plr_info[i,7] = "Left"
      plr_info[i,j] = 0
    }
  }
}

for(i in 1:224){
  for(j in 2:6){
    if(plr_info[i,j]==0){
      for(k in j:6){
        plr_info[i,k]=0
      }
    }
  }
}
for(i in 1:224){
    if(grepl("Right", plr_info[i,7])==FALSE&&grepl("Left", plr_info[i,7])==FALSE){
      plr_info[i,7]=NA
    }
}

plr_info = transform(plr_info, Birth = as.Date(Birth), 
          Height = as.numeric(gsub("cm", "", Height)), 
          Weight = as.numeric(gsub("kg", "", Weight)),
          Spike = as.numeric(gsub("cm", "", Spike)),
          Block = as.numeric(gsub("cm", "", Block)))

plr_info
```

## Players' age

```{r}
library("lubridate")
library(dplyr)
floor(time_length(difftime("2023-11-09", "1996-03-20"), "years"))


plr_info = plr_info %>% 
  mutate(Ages = floor(time_length(difftime("2023-11-09", Birth), "years")), .after = Birth)

plr_info = cbind(data.frame(Name = best_WS_data$Name, ShirtNumber = best_WS_data$ShirtNumber, Team = best_WS_data$Team), plr_info)
```